"""add property_unlocks, parking_type, payment settings

Revision ID: 2f3afde6c4ec
Revises: bb98ae367d2a
Create Date: 2026-07-28 21:50:26.838077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f3afde6c4ec'
down_revision: Union[str, None] = 'bb98ae367d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_unlocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='unlockstatus'), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'property_id', name='uq_unlock_user_property')
    )
    op.create_index(op.f('ix_property_unlocks_id'), 'property_unlocks', ['id'], unique=False)
    op.create_index(op.f('ix_property_unlocks_property_id'), 'property_unlocks', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_unlocks_user_id'), 'property_unlocks', ['user_id'], unique=False)
    op.add_column('broker_settings', sa.Column('payment_qr_image_url', sa.String(length=500), nullable=True))
    op.add_column('broker_settings', sa.Column('payment_phone', sa.String(length=20), nullable=True))
    op.add_column('broker_settings', sa.Column('unlock_fee', sa.Float(), nullable=False, server_default='20'))
    op.add_column('properties', sa.Column('parking_type', sa.Enum('NONE', 'OPEN', 'CLOSED', name='parkingtype'), nullable=False, server_default='NONE'))
    # Preserve existing data: anything that had parking (bool) becomes "open"
    # rather than silently losing that info when has_parking is dropped.
    # Note: SQLAlchemy's Enum column stores the member NAME (uppercase),
    # not its lowercase .value, so this must write 'OPEN' not 'open'.
    op.execute("UPDATE properties SET parking_type = 'OPEN' WHERE has_parking = 1")
    op.drop_column('properties', 'has_parking')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('has_parking', sa.BOOLEAN(), nullable=False, server_default='0'))
    op.execute("UPDATE properties SET has_parking = 1 WHERE parking_type != 'NONE'")
    op.drop_column('properties', 'parking_type')
    op.drop_column('broker_settings', 'unlock_fee')
    op.drop_column('broker_settings', 'payment_phone')
    op.drop_column('broker_settings', 'payment_qr_image_url')
    op.drop_index(op.f('ix_property_unlocks_user_id'), table_name='property_unlocks')
    op.drop_index(op.f('ix_property_unlocks_property_id'), table_name='property_unlocks')
    op.drop_index(op.f('ix_property_unlocks_id'), table_name='property_unlocks')
    op.drop_table('property_unlocks')
    # ### end Alembic commands ###
