"""add lat/lng columns to properties

Revision ID: dc216813fd0c
Revises: 2f3afde6c4ec
Create Date: 2026-07-28 23:08:10.598100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc216813fd0c'
down_revision: Union[str, None] = '2f3afde6c4ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'longitude')
    op.drop_column('properties', 'latitude')
    # ### end Alembic commands ###
